variables:
  GIT_STRATEGY: clone

stages:
  - mirror
  - publish

mirror-job:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apt update
    - apt install -y git
    - echo "Pulling ssh key"
    - mkdir ~/.ssh
    - cp /builds/katalogue/katalogue.tmp/SSH_KEY_GITHUB ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t ecdsa,ed25519,rsa -H github.com >> ~/.ssh/known_hosts
    - git config --global user.email "kd8bny@gmail.com"
    - git config --global user.name "Daryl Bennett"
  script:
    - git remote add github git@github.com:kd8bny/katalogue.git
    - git checkout -b $CI_COMMIT_BRANCH
    - git branch
    - git push -u github $CI_COMMIT_BRANCH

aur-git-job:
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apt update
    - apt install -y git
    - echo "Pulling ssh key"
    - mkdir ~/.ssh
    - cp /builds/katalogue/katalogue.tmp/SSH_KEY_AUR ~/.ssh/id_rsa
    - cp /builds/katalogue/katalogue.tmp/SSH_CONFIG_AUR ~/.ssh/config
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t ecdsa,ed25519,rsa -H aur.archlinux.org >> ~/.ssh/known_hosts
    - git config --global user.email "kd8bny@gmail.com"
    - git config --global user.name "Daryl Bennett"
  script:
    - mkdir /katalogue_aur/; cd /katalogue_aur/
    - git clone ssh://aur@aur.archlinux.org/katalogue-git.git
    - cd katalogue-git
    - export VERSION=r$(git rev-list --count HEAD).$CI_COMMIT_SHORT_SHA
    - echo $VERSION
    - git branch
    - sed -i "4 c pkgver=$VERSION" PKGBUILD
    - sed -i "3 c pkgver=$VERSION" .SRCINFO
    - head PKGBUILD
    - head .SRCINFO
    - git push origin master
  needs:
    - mirror-job
