variables:
  GIT_STRATEGY: clone

stages:
  # - test
  # - build
  - mirror
  - publish

build-job:
  tags:
    - unstable
  stage: build
  before_script:
    - apt update
    - apt install -y curl sudo git python3
    # - curl 'https://invent.kde.org/sdk/kde-builder/-/raw/master/scripts/initial_setup.sh' > initial_setup.sh
    # - chmod +x initial_setup.sh
    # - ./initial_setup.sh
    - mkdir -p ~/.local/share
    - cd ~/.local/share
    - git clone https://invent.kde.org/sdk/kde-builder.git
    - mkdir ~/.local/bin
    - ln -sf ~/.local/share/kde-builder/kde-builder ~/.local/bin
    - kde-builder --install-distro-packages
    # - apt install -y clang cmake extra-cmake-modules qt6-base-dev qml-qt6 qt6-declarative-dev qt6-svg-dev
  script:
    - mkdir build
    - pwd
    - ls
    - cmake .
    - cmake --build build --config Debug --target all --

# test-job:
  # tags:
  #   - unstable
#   stage: test
#   before_script:
#     - apt update
#     - apt install -y cmake

mirror-job:
  stage: publish
  before_script:
    - apt update
    - apt install -y git
    - echo "Pulling ssh key"
    - mkdir ~/.ssh
    - cp /builds/katalogue/katalogue.tmp/SSH_KEY_GITHUB ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t ecdsa,ed25519,rsa -H github.com >> ~/.ssh/known_hosts
    - git config --global user.email "kd8bny@gmail.com"
    - git config --global user.name "Daryl Bennett"
  script:
    - git remote add github git@github.com:kd8bny/katalogue.git
    - git checkout -b $CI_COMMIT_BRANCH
    - git branch
    # - git push -u github $CI_COMMIT_BRANCH

aur-git-job:
  stage: publish
  before_script:
    - apt update
    - apt install -y git
    - echo "Pulling ssh key"
    - mkdir ~/.ssh
    - cp /builds/katalogue/katalogue.tmp/SSH_KEY_AUR ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -t ecdsa,ed25519,rsa -H aur.archlinux.org >> ~/.ssh/known_hosts
    - git config --global user.email "kd8bny@gmail.com"
    - git config --global user.name "Daryl Bennett"
  script:
    - mkdir /katalogue_aur/; cd /katalogue_aur/
    - git clone https://aur.archlinux.org/katalogue-git.git
    - cd katalogue-git
    # - git remote add aur aur@aur.archlinux.org/katalogue-git.git
    - export VERSION=r$(git rev-list --count HEAD).$CI_COMMIT_SHORT_SHA
    - echo $VERSION
    - git branch
    - sed -i "4 c pkgver=$VERSION" PKGBUILD
    - sed -i "3 c pkgver=$VERSION" .SRCINFO
    - head PKGBUILD
    - head .SRCINFO
    # - git push origin master
  needs:
    - mirror-job
