// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KATALOGUE_VERSION_H
#define KATALOGUE_VERSION_H

#define KATALOGUE_VERSION_STRING "0.1"
#define KATALOGUE_VERSION_MAJOR 0.1
#define KATALOGUE_VERSION_MINOR 0.1
#define KATALOGUE_VERSION_PATCH 0.1
#define KATALOGUE_VERSION ((0.1<<16)|(0.1<<8)|(0.1))

#endif
